from naptan import NaptanMapsProvider
from oxontime import OxontimeMapsProvider
from osm import OSMMapsProvider
from oxpoints import OxpointsMapsProvider
from postcodes import PostcodesMapsProvider
from ldb import LiveDepartureBoardPlacesProvider
