from naptan import NaptanMapsProvider
from acislive import ACISLiveMapsProvider
from osm import OSMMapsProvider
from oxpoints import OxpointsMapsProvider
from postcodes import PostcodesMapsProvider
from ldb import LiveDepartureBoardPlacesProvider
from bbc_tpeg import BBCTPEGPlacesProvider